language: node_js

node_js:
  - stable

install:
  - npm install

script:
  - nyc npm run test:unit && nyc report --reporter=text-lcov | coveralls

after_script:
  - COVERALLS_REPO_TOKEN=$coveralls_repo_token npm run coveralls
